#!/usr/bin/env bash
# PolyBench/C on LVX: compiler performance tracking, with a correctness gate.
#
#   ./harness/run.sh                            # lvx-2, -O2, MINI, double
#   ARCH=lvx-1 OPT=3 ./harness/run.sh
#   DATASET=SMALL TYPE=float ./harness/run.sh
#   STATIC_ONLY=1 ./harness/run.sh              # build + static metrics, no ISS
#   ONLY='gemm syrk 2mm' ./harness/run.sh       # a subset
#   LVX_CPU=minor ./harness/run.sh              # pipeline model, slow
#   ./harness/compare.sh results/A.tsv results/B.tsv
#
# Writes one TSV row per kernel to results/<arch>-O<opt>-<dataset>-<type>.tsv
# and a human summary to stdout.  Commit the results: the series is the point.
#
# WHY THE HEADLINE NUMBER IS THE GUEST'S OWN, NOT gem5's
#
# PolyBench brackets the kernel and nothing else with polybench_start_instruments
# / polybench_stop_instruments, and on LVX that reads $frcc, the 64-bit
# free-running cycle counter (utilities/polybench.c, patched -- it is where
# x86's RDTSC was).  So the guest prints the cycle count of the KERNEL, with
# array initialisation, allocation and printf excluded.  gem5's
# system.cpu.numCycles covers the whole program and at MINI is dominated by
# everything that is not the kernel -- for gemm, 109,316 kernel cycles inside
# 208,020 total.  Tracking the gem5 figure would mean tracking crt0 and malloc.
#
# Both are recorded: kernel_cycles is what a compiler change should move, and
# prog_cycles is the cross-check -- if the kernel figure moves and the program
# figure does not, suspect the measurement rather than the compiler.
#
# WHY CYCLES AND NOT TIME.  The ISS is deterministic: the same ELF yields the
# same counts every run, on any host, with no quiet-machine ritual and no
# averaging.  That makes it a better instrument for tracking a compiler than
# real hardware.
#
# WHY EVERY RUN IS DIFFED.  A miscompile can look like a speed-up, and on this
# target it has: a stale divv.o with eight invalid opcodes in it made a gemm
# prototype produce wrong results while still "running".  PolyBench ships no
# reference output, but it ships something better -- POLYBENCH_DUMP_ARRAYS, and
# kernels that read no input at all -- so the oracle is GENERATED by running the
# same source natively on x86 (harness/make-reference.sh).  A row whose
# `correct' column is neither ok nor fp-N is not a performance result.
#
# Two ELFs are built per kernel, which is PolyBench's own design: the timed one
# has print_array behind POLYBENCH_DCE_ONLY_CODE, so the computation is kept
# alive but never printed, and the dumping one prints it.  Timing a dumping
# build would measure printf.
set -u

here="$(cd "$(dirname "$0")" && pwd)"
repo="$(dirname "$here")"
CSW="$(cd "$repo/.." && pwd)"

ARCH=${ARCH:-lvx-2}

# BOTH FP WIDTHS BY DEFAULT.  32-bit and 64-bit FP are not two settings of one
# benchmark here, they are the measurement: a 128-bit LVX lane holds four floats
# or two doubles, so the float/double ratio per kernel is how much the
# vectorizer actually got.  A run that reports only one width cannot show that,
# so TYPE is a LIST and defaults to both.  One TSV per type -- the type is in
# the filename and in every row -- and harness/fpcompare.sh puts the two side by
# side.  TYPE=float runs just the one.
TYPES=${TYPE:-"float double"}
if [ "$(set -- $TYPES; echo $#)" -gt 1 ]; then
    rc=0
    for t in $TYPES; do
        echo "=== $t ==="
        TYPE=$t "$0" "$@" || rc=$?
        echo
    done
    exit $rc
fi
TYPE=$TYPES
OPT=${OPT:-2}
DATASET=${DATASET:-MINI}
core=${ARCH#lvx-}
STATIC_ONLY=${STATIC_ONLY:-0}
ONLY=${ONLY:-}
TIMEOUT=${TIMEOUT:-5400}

TOOLS=${LVX_TOOLS:-$CSW/lvx-toolchain/bin}
GCC=$TOOLS/lvx-mbr-gcc
OBJDUMP=$TOOLS/lvx-mbr-objdump
SIZE=$TOOLS/lvx-mbr-size
GEM5=${GEM5:-$CSW/lvx-gem5/build/gem5-lvx$core.opt}
GEM5_CFG=${GEM5_CFG:-$CSW/lvx-gem5/tests/lvx/run_lvx.py}
LDSCRIPTS=${LDSCRIPTS:-$CSW/lvx-newlib/libgloss/lvx-mbr/linker_scripts}

case "$TYPE" in
    float)  tmacro=DATA_TYPE_IS_FLOAT  ;;
    double) tmacro=DATA_TYPE_IS_DOUBLE ;;
    int)    echo "TYPE=int does not build: PolyBench defines SCALAR_VAL only under" >&2
            echo "  DATA_TYPE_IS_FLOAT and DATA_TYPE_IS_DOUBLE, and every kernel that" >&2
            echo "  uses it fails to compile with -DDATA_TYPE_IS_INT.  Measured" >&2
            echo "  2026-10-09: 0 of 30 kernels build.  Upstream limitation, not LVX." >&2
            exit 2 ;;
    *) echo "TYPE must be float or double (got $TYPE)" >&2; exit 2 ;;
esac

# -T lvx-sim.ld supplies sbrk's _heap_start/_heap_end; without it a hosted link
# leaves them undefined and malloc has no heap -- and PolyBench allocates every
# array through it (xmalloc, patched to memalign because newlib has no
# posix_memalign).  Unlike MiBench, these kernels are strict C99 and need no
# -std=gnu89 -fpermissive.  FP contraction is left at GCC's default ON: ffma is
# the instruction worth measuring, and the reference absorbs the difference
# (harness/dumpcmp.py).
CFLAGS="-O$OPT -march=$ARCH -I$repo/utilities"
LDFLAGS="-T lvx-sim.ld -L$LDSCRIPTS -lm"
DEFS="-D${DATASET}_DATASET -D$tmacro"

for t in "$GCC" "$OBJDUMP" "$SIZE"; do
    [ -x "$t" ] || { echo "missing tool: $t" >&2; exit 2; }
done
if [ "$STATIC_ONLY" != 1 ]; then
    [ -x "$GEM5" ] || { echo "missing ISS: $GEM5" >&2; exit 2; }
fi

refdir="$repo/reference-output/$(echo "$DATASET" | tr A-Z a-z)-$TYPE"
[ -d "$refdir" ] || echo "note: no reference in $refdir -- run harness/make-reference.sh" >&2

outdir="$repo/results"; mkdir -p "$outdir"
tsv="$outdir/$ARCH-O$OPT-$(echo "$DATASET" | tr A-Z a-z)-$TYPE.tsv"
work=$(mktemp -d); trap 'rm -rf "$work"' 0 1 2 3 15

HEADER='kernel\tarch\topt\tdataset\ttype\tcorrect\tkernel_cycles\tprog_cycles\tbundles_dyn\ttext_bytes\tinsns_static\tbundles_static\tkernel_insns\tsimd_insns\tscalar_fma'

# Rows are collected here and merged into $tsv at the end.  Writing $tsv
# directly would make an ONLY= run DESTROY a full baseline, since the path
# depends only on arch/opt/dataset/type: a one-kernel re-run would open the
# same file and truncate it.  That happened in lvx-mibench on 2026-10-09 and
# cost a complete 13-row baseline.  Merging makes the re-run do the useful
# thing -- replace that kernel's row, keep the rest.
rows="$work/rows.tsv"; : > "$rows"
printf '%-16s %-10s %14s %14s %10s %8s %6s %6s\n' \
       KERNEL CORRECT KERNEL_CYC PROG_CYC TEXT KINSNS SIMD SFMA

while read -r path; do
    case "$path" in ''|\#*) continue ;; esac
    path=${path#./}
    dir=$(dirname "$path"); name=$(basename "$path" .c)
    [ -n "$ONLY" ] && ! grep -qw "$name" <<<"$ONLY" && continue

    bdir="$work/$name"; mkdir -p "$bdir"
    row() { printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
            "$name" "$ARCH" "$OPT" "$DATASET" "$TYPE" "$1" \
            "${2:-}" "${3:-}" "${4:-}" "${5:-}" "${6:-}" "${7:-}" \
            "${8:-}" "${9:-}" "${10:-}" >> "$rows"; }

    # --- the timed build: computation alive, print_array behind DCE_ONLY_CODE
    if ! $GCC $CFLAGS -I"$repo/$dir" "$repo/utilities/polybench.c" "$repo/$path" \
         $DEFS -DPOLYBENCH_CYCLE_ACCURATE_TIMER $LDFLAGS -o "$bdir/t.elf" -lm \
         > "$bdir/build-t.log" 2>&1; then
        printf '%-16s %-10s %14s %14s %10s %8s %6s %6s\n' \
               "$name" BUILDFAIL - - - - - -
        row buildfail; continue
    fi

    # --- static metrics: free, and defined even when the ISS is too slow
    text=$($SIZE -A "$bdir/t.elf" | awk '$1==".text"{print $2}')
    $OBJDUMP -d "$bdir/t.elf" > "$bdir/dis.txt" 2>/dev/null
    insns=$(grep -cE '^\s+[0-9a-f]+:' "$bdir/dis.txt")
    sbundles=$(grep -c ';;' "$bdir/dis.txt")
    # Lane-wise SIMD instructions, counted by their lane-shape suffix: dp=2x64,
    # wq=4x32, ho=8x16, bx=16x8, all of them 128 bits (the letter is the lane
    # COUNT, not the width).  This is the metric that says whether the
    # vectorizer fired at all, and it is why it is worth having next to a cycle
    # count: at MINI, lvx-2 emits 26 SIMD instructions for gemm against lvx-1's
    # zero, carries 14% more text -- and runs 1.4% faster, because its scalar
    # ffmaw count is UNCHANGED.  The vectorizer took the elementwise
    # `C[i][j] *= beta' loop and left the multiply-accumulate nest that is the
    # actual kernel alone, so the vector code is additional rather than a
    # replacement.  A cycle count alone cannot distinguish that from "the
    # vectorizer never ran"; this column can.
    #
    # SCOPED TO THE KERNEL'S OWN OBJECT, not the linked image.  Counting over
    # the ELF reported 6 SIMD instructions for bicg on lvx-1 -- a core that has
    # no lane-wise arithmetic at all.  They were newlib's and libgcc's: the
    # lvx-1 data-movement family (splatwq, evenwq, oddwq, ...) carries the same
    # lane-shape suffixes, and libgcc's own vector helpers get linked in.  A
    # metric meant to say "did the vectorizer touch this kernel" cannot be read
    # off an image that is mostly library code, so it is counted on the kernel
    # translation unit alone -- also the right scope, since
    # utilities/polybench.c is instrumentation rather than kernel.
    $GCC $CFLAGS -I"$repo/$dir" $DEFS -DPOLYBENCH_CYCLE_ACCURATE_TIMER \
         -c "$repo/$path" -o "$bdir/k.o" > /dev/null 2>&1
    $OBJDUMP -d "$bdir/k.o" > "$bdir/kdis.txt" 2>/dev/null
    kinsns=$(grep -cE '^\s+[0-9a-f]+:' "$bdir/kdis.txt")
    simd=$(grep -coE '\b[a-z]+(dp|wq|ho|bx)\b' "$bdir/kdis.txt" || true)
    sfma=$(grep -coE '\b(ffmaw|ffmad|fmulw|fmuld|ffmsw|ffmsd)\b' "$bdir/kdis.txt" || true)

    if [ "$STATIC_ONLY" = 1 ]; then
        printf '%-16s %-10s %14s %14s %10s %8s %6s %6s\n' \
               "$name" static - - "$text" "$kinsns" "$simd" "$sfma"
        row static '' '' '' "$text" "$insns" "$sbundles" "$kinsns" "$simd" "$sfma"; continue
    fi

    # --- the dumping build, for the correctness gate
    $GCC $CFLAGS -I"$repo/$dir" "$repo/utilities/polybench.c" "$repo/$path" \
         $DEFS -DPOLYBENCH_DUMP_ARRAYS $LDFLAGS -o "$bdir/d.elf" -lm \
         > "$bdir/build-d.log" 2>&1

    # stdin MUST be redirected even though no kernel reads any.  gem5 shares
    # our stdin, and ours is utilities/benchmark_list being read by the loop
    # around this -- without a redirect the guest consumes the rest of the list
    # and the run stops early.  (lvx-mibench hit exactly this; it presented as
    # adpcm reading the benchmark table as PCM.)
    #
    # The two streams are kept apart rather than merged with 2>&1: gem5's own
    # info/warn go to stderr, including "Increasing stack size by one page"
    # which it emits repeatedly MID-RUN, while stdout carries only its banner
    # and the guest's bytes.  Merging interleaves diagnostics into the guest's
    # output and no positional extraction can recover it.  This is also why
    # POLYBENCH_DUMP_TARGET is patched to stdout on LVX: the dump prints a whole
    # array with no newline until the end, so a mid-line intrusion on stderr
    # could not even be filtered by line prefix.
    ( cd "$bdir" && timeout "$TIMEOUT" "$GEM5" --outdir=m5t "$GEM5_CFG" \
             "$bdir/t.elf" < /dev/null ) > "$bdir/t.out" 2> "$bdir/t.err"
    rc=$?

    python3 "$here/guest-output.py" "$bdir/t.out" "$bdir/t.guest" 2>/dev/null
    kcyc=$(grep -aoE '^[0-9]+$' "$bdir/t.guest" 2>/dev/null | tail -1)
    stats="$bdir/m5t/stats.txt"
    pcyc=$(awk '$1=="system.cpu.numCycles"{print $2}' "$stats" 2>/dev/null)
    dynb=$(awk '$1=="simInsts"{print $2}' "$stats" 2>/dev/null)
    exited=$(grep -aoE 'code=-?[0-9]+' "$bdir/t.out" | tail -1)

    correct=unchecked
    if [ "$rc" -eq 124 ]; then
        correct=timeout
    elif [ "$exited" != "code=0" ]; then
        correct="exit${exited#code=}"
    elif [ ! -f "$bdir/d.elf" ]; then
        correct=dumpbuildfail
    elif [ ! -f "$refdir/$name.txt" ]; then
        correct=noref
    else
        ( cd "$bdir" && timeout "$TIMEOUT" "$GEM5" --outdir=m5d "$GEM5_CFG" \
                 "$bdir/d.elf" < /dev/null ) > "$bdir/d.out" 2> "$bdir/d.err"
        drc=$?
        python3 "$here/guest-output.py" "$bdir/d.out" "$bdir/d.guest" 2>/dev/null
        if [ "$drc" -eq 124 ]; then
            correct=dumptimeout
        else
            correct=$(python3 "$here/dumpcmp.py" "$refdir/$name.txt" "$bdir/d.guest")
            case "$correct" in
            MISMATCH*)
                # ESCALATION, not an excuse.  The reference is built
                # -ffp-contract=off and the LVX side is not, so a kernel whose
                # arithmetic amplifies a last-bit difference can diverge
                # arbitrarily far without anything being wrong with the code.
                # gramschmidt does exactly that: classical Gram-Schmidt in
                # float subtracts nearly-equal projections and normalises by a
                # norm that approaches zero, so 448 of its 1516 printed values
                # differ -- with sign flips -- purely from LVX emitting five
                # ffma/ffms where x86 GCC emits none.
                #
                # Rather than whitelist that kernel, PROVE it: rebuild the
                # dumping ELF with contraction off, which is exactly how the
                # reference was built, and compare again.  If it now matches
                # bit-for-bit the code generation is verified and the verdict is
                # fp-contract; if it still differs, MISMATCH stands.  A real
                # miscompile -- a bad lane permutation, a stale object with
                # wrong encodings -- fails both ways, so this cannot launder
                # one.  Only paid when the strict compare already failed.
                reason=$correct
                $GCC $CFLAGS -I"$repo/$dir" -ffp-contract=off \
                     "$repo/utilities/polybench.c" "$repo/$path" \
                     $DEFS -DPOLYBENCH_DUMP_ARRAYS $LDFLAGS -o "$bdir/s.elf" -lm \
                     > "$bdir/build-s.log" 2>&1
                if [ -f "$bdir/s.elf" ]; then
                    ( cd "$bdir" && timeout "$TIMEOUT" "$GEM5" --outdir=m5s \
                             "$GEM5_CFG" "$bdir/s.elf" < /dev/null ) \
                        > "$bdir/s.out" 2> "$bdir/s.err"
                    python3 "$here/guest-output.py" "$bdir/s.out" "$bdir/s.guest" 2>/dev/null
                    strict=$(python3 "$here/dumpcmp.py" "$refdir/$name.txt" "$bdir/s.guest")
                else
                    strict="MISMATCH: contraction-off build failed"
                fi
                case "$strict" in
                    ok|fp-*) correct=fp-contract
                             echo "$name: fp-contract -- exact with -ffp-contract=off; with it on, $reason" \
                                  >> "$work/contract.log" ;;
                    *)       correct=MISMATCH
                             echo "$name: $reason" >> "$work/mismatch.log"
                             echo "$name: and still wrong with -ffp-contract=off: $strict" \
                                  >> "$work/mismatch.log" ;;
                esac ;;
            esac
        fi
    fi

    printf '%-16s %-10s %14s %14s %10s %8s %6s %6s\n' \
           "$name" "$correct" "${kcyc:-?}" "${pcyc:-?}" "$text" "$kinsns" \
           "$simd" "$sfma"
    row "$correct" "${kcyc:-}" "${pcyc:-}" "${dynb:-}" "$text" "$insns" "$sbundles" "$kinsns" "$simd" "$sfma"
done < "$repo/utilities/benchmark_list"

# Merge: this run's rows win, rows for kernels it did not run are kept, and the
# order follows benchmark_list so two files always line up for compare.sh.
if [ -f "$tsv" ]; then
    # NOT `if (FNR>1)' on $rows: $rows carries no header line, so that guard
    # skipped its FIRST row and left that one unmarked -- the baseline's copy
    # was then appended as well and the kernel appeared TWICE in the merged
    # file, with the stale row sorting first.  The merge exists to stop an
    # ONLY= re-run from destroying a baseline, which it did; it was silently
    # duplicating instead.  Found 2026-10-09 by an ONLY=gramschmidt re-run.
    awk -F'\t' 'NR==FNR { seen[$1]=1; next }
                 FNR>1 && !($1 in seen) { print }' "$rows" "$tsv" >> "$rows"
fi
awk '/^[^#]/ && NF { sub(/^\.\//,""); n=$0; sub(/.*\//,"",n); sub(/\.c$/,"",n);
                     if (n!="") print n }' "$repo/utilities/benchmark_list" \
    > "$work/known"
{
    printf "$HEADER\n"
    while read -r n; do awk -F'\t' -v n="$n" '$1==n' "$rows"; done < "$work/known"
    awk -F'\t' 'NR==FNR { k[$1]=1; next } !($1 in k) && $1!="kernel" { print }' \
        "$work/known" "$rows"
} > "$tsv.new" && mv "$tsv.new" "$tsv"

echo
if [ -f "$work/contract.log" ]; then
    echo "fp-contract -- code generation verified against the reference with"
    echo "-ffp-contract=off; the divergence is FMA rounding this kernel amplifies:"
    sed 's/^/  /' "$work/contract.log"
    echo
fi
if [ -f "$work/mismatch.log" ]; then
    echo "MISMATCHES -- these rows are not performance results:"
    sed 's/^/  /' "$work/mismatch.log"
    echo
fi
echo "wrote $tsv"
